#!/bin/bash

set -e

zero_sha="0000000000000000000000000000000000000000"

while read -r _local_ref local_sha _remote_ref remote_sha; do
	# Determine commit range
	if [[ "$remote_sha" == "$zero_sha" ]]; then
		# New branch or first push
		commits=$(git rev-list "$local_sha")
	else
		commits=$(git rev-list "$remote_sha".."$local_sha")
	fi

	for commit in $commits; do
		message=$(git log -1 --format=%B "$commit")

		if [[ "$message" == fixup!* ]]; then
			echo -e "\e[31mError - fixup commit pending: \e[46m\e[31m$message\e[0m"
			echo -e "\e[31mPlease squash or autosquash before pushing.\e[0m"
			exit 1
		fi
	done
done

exit 0
